# Shougo: ---------------------------
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = 'source ~/.vim/rc/plugins/neocomplete.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
hook_add = '''
    " <C-k>でsnippetの展開
    let g:neosnippet#snippets_directory='~/.vim/snippets/'
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
# include周りの補完, c, c++は必須
repo = 'Shougo/neoinclude.vim'
on_i = 1
filetypes  =  ['c', 'cpp']

[[plugins]]
# Xcode化
repo = 'msanders/cocoa.vim'
on_i = 1
filetypes  =  ['m', 'swift', 'cpp']

# Base Tools: ---------------------------
[[plugins]]
# 非同期コンパイル(OmniSharpを自動で起動もしてくれる)
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
hook_source = 'source ~/.vim/rc/plugins/vim-quickrun.rc.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
on_source = 'vim-quickrun.vim'
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config['watchdogs_checker/_'] = {'outputter/quickfix/open_cmd': ''}
  let g:quickrun_config['watchdogs_checker/jshint'] = {'cmdopt': '--config `/.jshintrc'}
  " ファイルの保存時にチェックを行う
  let g:watchdogs_check_BufWritePost_enable = 1
'''
hook_post_source = '''
  call watchdogs#setup(g:quickrun_config)
'''

[[plugins]]
repo = 'cohama/vim-hier'
on_source = 'vim-quickrun.vim'

[[plugins]]
# Need to `brew install ctags`
repo = 'soramugi/auto-ctags.vim'
on_i = 1
commands = 'TagbarToggle'
hook_add = '''
    let g:tagbar_width = 20
    nmap <Leader>t :TagbarToggle<CR>
'''

[[plugins]]
# 構文チェック
repo = 'scrooloose/sYntastic.git'
on_i = 1

[[plugins]]
# c, cpp complement
repo = 'justmao945/vim-clang'
on_i = 1
filetypes  =  ['c', 'cpp']

[[plugins]]
# cs complement
repo = 'OmniSharp/omnisharp-vim'
on_i = 1
filetypes  =  ['cs', 'csi', 'csx']
windows = 'msbuild server/OmniSharp.sln'
mac = 'xbuild server/OmniSharp.sln'
unix = 'xbuild server/OmniSharp.sln'
hook_add = '''
    inoremap <expr> <CR>    pumvisible() ? "\<C-y>" : "\<CR>"
    inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
    " ポップアップ削除
    inoremap <expr><C-h> neocomplcache#smart_close_popup().”\<C-h>”
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_i = 1

# Convenience Tools: ---------------------------
[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = 'nnoremap <Leader>s :Switch<CR>'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = '<C-_>'

[[plugins]]
# markdown preview
repo = 'kannokanno/previm' # TODO: 使えない
on_map = '<Space>'
on_ft = 'md'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = 'l'
hook_add = '''
    let g:netrw_nogx = 1
    nmap go <Plug>(openbrowser-smart-search)
    vmap go <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
on_map = 'm'
hook_add = '''
    nnoremap mm :NoShowMarks!<CR>:DoShowMarks!<CR>
'''

[[plugins]]
repo = 'haya14busa/vim-easymotion'
on_map = '<Space>'
hook_source = 'source ~/.vim/rc/plugins/vim-easymotion.rc.vim'

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = 'nmap U :<C-u>GundoToggle<CR>'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
# Need 'brew install cmigemo' (gvim限定)
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'kana/vim-altr'
hook_add = 'nmap <Leader>a <Plug>(altr-forward)'
on_map = '<Plug>(altr-'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
'''

[[plugins]]
# No lazy but use lazy
repo = 'kana/vim-smartchr'
hook_add = '''
    inoremap <buffer> <expr> = smartchr#loop(' = ', ' == ', '=')
    inoremap <buffer> <expr> , smartchr#loop(', ', ',')
    inoremap <buffer> <expr> - smartchr#loop('- ', '--')
    inoremap <buffer> <expr> : smartchr#loop(': ', '::')
    inoremap <buffer> <expr> ! smartchr#loop('! ', '!!')
    inoremap <buffer> <expr> * smartchr#loop('* ', '*')
    inoremap <buffer> <expr> + smartchr#loop('+ ', '++')
    inoremap <buffer> <expr> ? smartchr#loop('? ', '??')
    inoremap <buffer> <expr> { smartchr#loop('{', '{<CR>}')
'''

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Space>'
hook_add = '''
    nmap <Space>m <Plug>(quickhl-manual-this)
    xmap <Space>m <Plug>(quickhl-manual-this)
    nmap <Space>M <Plug>(quickhl-manual-reset)
    xmap <Space>M <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_map = 'S'

# Go ---------------------------
[[plugins]]
repo = 'fatih/vim-go'

# Html ---------------------------
[[plugins]]
repo = 'mattn/emmet-vim'

