# Shougo: ---------------------------

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
hook_add = '''
    " <C-k>でsnippetの展開
    let g:neosnippet#snippets_directory='~/.vim/snippets/'
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
'''

# include周りの補完, c, c++は必須
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1
filetypes = ['c', 'cpp', 'm', 'mm']
hook_add = '''
    let g:neoinclude#_paths = '/Applications/Cocos/Cocos2d-x/cocos2d-x-3.6/cocos'
    let g:neoinclude#_paths = '/usr/local/Cellar/boost'
'''


# Base Tools: ---------------------------

# 非同期コンパイル(OmniSharpを自動で起動もしてくれる)
[[plugins]]
repo = 'tpope/vim-dispatch'
on_i = 1

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
hook_source = 'source ~/.vim/rc/plugins/quickrun.rc.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
on_source = 'vim-quickrun.vim'
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config['watchdogs_checker/_'] = {'outputter/quickfix/open_cmd': ''}
  let g:quickrun_config['watchdogs_checker/jshint'] = {'cmdopt': '--config `/.jshintrc'}
  " ファイルの保存時にチェックを行う
  let g:watchdogs_check_BufWritePost_enable = 1
'''
hook_post_source = '''
  call watchdogs#setup(g:quickrun_config)
'''

[[plugins]]
repo = 'cohama/vim-hier'
on_source = 'vim-quickrun.vim'

# Need to `brew install ctags`
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_i = 1
commands = 'TagbarToggle'
hook_add = '''
    let g:tagbar_width = 20
    nmap <Leader>t :TagbarToggle<CR>
'''

[[plugins]]
repo = 'vim-scripts/gtags.vim'
on_i = 1
hook_source = 'source ~/.vim/rc/plugins/gtags.rc.vim'

# 構文チェック
[[plugins]]
repo = 'scrooloose/sYntastic.git'
on_i = 1

# 英単語辞書補完(重いのでoff)
# [[plugins]]
# repo = 'ujihisa/neco-look'
# on_i = 1
# filetypes  =  ['*']

# c, cpp complement
# [[plugins]]
# repo = 'justmao945/vim-clang'
# on_i = 1
# filetypes  =  ['c', 'cpp']

# cs complement
# 自動でserverセットアップしてくれる(してくれない場合手動: plugin下のserverへ行き, xbuild)
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_i = 1
filetypes  =  ['cs', 'csi', 'csx']
windows = 'msbuild server/OmniSharp.sln'
mac     = 'xbuild server/OmniSharp.sln'
unix    = 'xbuild server/OmniSharp.sln'
hook_add = '''
    inoremap <expr> <CR>    pumvisible() ? "\<C-y>" : "\<CR>"
    inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
    " ポップアップ削除
    inoremap <expr><C-h> neocomplcache#smart_close_popup().”\<C-h>”
'''

# TODO: 使いたい
# [[plugins]]
# repo = 'hewes/unite-gtags'

# make plugin(:LayoutPlugin xxx.vim)
[[plugins]]
repo = 'mopp/layoutplugin.vim'

# Need redmine
# [[plugins]]
# repo = 'kana/vim-metarw'

# Convenience Tools: ---------------------------
[[plugins]]
repo = 'yuratomo/w3m.vim'
hook_add = '''
    let g:w3m#external_browser = 'google-chrome'
'''

# [[plugins]]
# repo = 'simeji/vim-chatworker.git'
# hook_add = '''
#     let g:chatwork_token = ''
# '''

# default key is 'gs'
[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = '<C-_>'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
    let g:netrw_nogx = 1
    nmap go <Plug>(openbrowser-smart-search)
    vmap go <Plug>(openbrowser-smart-search)
    command! OpenRedMineTicket execute "OpenBrowser" expand("aaa")
'''

[[plugins]]
repo = 'sjl/gundo.vim'
hook_add = 'nmap U :<C-u>GundoToggle<CR>'

# Need 'brew install cmigemo' (gvim限定)
[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'kana/vim-altr'
hook_add = 'nmap <Leader>a <Plug>(altr-forward)'
on_map = '<Plug>(altr-'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
    nnoremap <Leader>cl :Calendar<Cr>
'''

# file shaping(:Align =)
[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'vim-scripts/TaskList.vim'
hook_add = '''
    nnoremap <Leader>T :TaskList<CR>
'''


# C++ ---------------------------


# Markdown ---------------------------

# preview
[[plugins]]
repo = 'kannokanno/previm'
on_map = '<Space>'
on_ft = 'md'
hook_add = '''
    let g:previm_open_cmd = 'open -a Safari'
'''


# Swift ---------------------------

[[plugins]]
repo = 'zebult/xcode.vim'
filetypes = ['m', 'mm', 'swift', 'cpp', 'h', 'hpp']
hook_add = '''
    let g:application_name = "Xcode7.2.1"
    nnoremap <silent> <Leader>X :XcodeProjectOpen<CR>
    nnoremap <silent> <Leader>x :XcodeFileOpen<CR>
    nnoremap <silent> <Leader>Q :XcodeClose<CR>
    nnoremap <silent> <Leader>e :XcodeFocus<CR>
'''

# Xcode化
# [[plugins]]
# repo = 'msanders/cocoa.vim'
# on_i = 1
# filetypes = ['m', 'swift', 'cpp', 'h', 'hpp']

# iOSシミュレータ使える??
# [[plugins]]
# repo = 'kballard/vim-swift'
# on_i = 1
# on_ft = ['m', 'swift', 'cpp', 'h', 'hpp']

# brew install sourcekitten
[[plugins]]
repo = 'mitsuse/autocomplete-swift'
on_i = 1
on_ft = 'swift'
# hook_source = 'autocmd FileType swift imap <buffer> <C-k> <Plug>(autocomplete_swift_jump_to_placeholder)' not use snip


# Go ---------------------------

[[plugins]]
repo = 'fatih/vim-go'


# Html ---------------------------

[[plugins]]
repo = 'mattn/emmet-vim'

# Game ---------------------------
[[plugins]]
repo = 'rbtnn/game_engine.vim'

[[plugins]]
repo = 'rbtnn/puyo.vim'

[[plugins]]
repo = 'rbtnn/mario.vim'

[[plugins]]
repo = 'rbtnn/reversi.vim'
